pipeline:
  build_docker_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t centos-build .
    when:
      event: [push, tag]

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=${DOCKER_PASSWORD} quay.io
      - docker tag centos-build quay.io/ukhomeofficedigital/centos-build:${DRONE_TAG}
      - docker tag centos-build quay.io/ukhomeofficedigital/centos-build:latest
      - docker push quay.io/ukhomeofficedigital/centos-build:${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/centos-build:latest
    when:
      event: tag

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
