pipeline:
  build_docker_image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t centos-build:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+centos_build" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag centos-build:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-build:$${DRONE_TAG}
      - docker tag centos-build:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-build:latest
      - docker push quay.io/ukhomeofficedigital/centos-build:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/centos-build:latest
    when:
      event: tag
